const data = [
    {
        "lado": "dark",
        "name": [ 'Darth vader','Darth Revan', 'Darth Sidious', 'Darth Maul', 'Darth Tyranus', 'Asajj ventress', 'Kylo Ren'],
        "desc": [
            'Após os acontecimentos de "Vingança dos Sith", o escolhido Anakin Skywalker se volta para o lado negro, se tornando um dos mais poderosos Sith que ja existiram, mesmo sendo limitado pelo seu corpo mecânico, Darth Vader ainda acumula grandes feitos com a Força, sendo derrotado pelo seu filho Luke, Darth Vader renega o lado sombrio e volta a ser um Jedi em "O retorno de Jedi".',

            'Revan começou sua jornada como um Jedi conhecido por sua habilidade excepcional com a Força e suas habilidades de combate. Ele ganhou destaque durante as Guerras Mandalorianas, um conflito entre a República Galáctica e os guerreiros Mandalorianos. Revan emergiu como um líder militar talentoso, capaz de inspirar seus seguidores e conduzir a República à vitória. No entanto, durante esse conflito, ele e seu amigo, Malak, foram corrompidos pelo poder do lado sombrio da Força. Eventualmente, ele foi traído por Darth Malak e capturado pela República. Por meio de uma intervenção Jedi, Revan teve sua memória apagada e foi reprogramado para acreditar que era um soldado da República. Assim, sua identidade como Sith foi escondida dele.',

            'Darth Sidious, ou Palpatine, foi o vilão da primeira trilogia de Star Wars, recebendo o cargo de Chanceler conseguiu ganhar a confiança do escolhido Anakin Skywalker e trouxe ele para o lado negro. Após a conversão e execução da Ordem 66, Sidious se tornou Imperador e deu inicio aos acontecimentos dos filmes, morto por Rey em Ascensão Skywalker.', 'Sendo um zabrak de Dathomir e filho de Mãe Talzin, Darth Maul foi treinado por Sidious antes de Darth Tyranus e Darth Vader, sendo considerado um excelente duelista Maul assassinou Qui-Gon Jinn em um combate dois contra um, sendo vencido por Obi-Wan Kenobi e sobrevivendo após ser partido ao meio. Regressa em Star Wars Rebels e após os acontecimentos da série é morto por Obi-Wan em Tatooine.',
            'Mestre de Quin-Gon Jinn e aprendiz de Yoda, acabou sendo considerado o ,melhor duelista de sua época, Conde Dookan tinha suas habilidades de sabre tão polidas ou até melhor que o próprio Mestre Yoda, após a "morte" de Darth Maul se tornou aprendiz de Sidious. Em um duelo dois contra um foi capaz de derrotar e humilhar Obi-Wan e Anakin sem dificuldades, após os acontecimentos das Guerras Clonicas foi morto por Anakin a mando de seu mestre Darth Sidious.',
        
            'Apesar de não ser uma Sith completa, Ventress foi treinada por Darth Tyranus, aparecendo pela primeira vez na série Clone Wars, teve sua origem entre as bruxas de Dathomir e na Ordem Jedi, após a morte de seu primeiro mestre se voltou para o lado sombrio, aonde permaneceu até Dookan a trair.',
            'Kylo Ren, tambem conhecido como Ben Solo, é filho de Han Solo e Leia e neto de Anakin Skywalker. Treinado como um Jedi por seu tio Luke Skywalker, Ben foi seduzido para o lado sombrio da Força pelo Líder Supremo Snoke, aspirando ser tão poderoso quanto seu avô, o Lorde Sith Darth Vader.Como Kylo Ren, ele se torna o mestre dos Cavaleiros de Ren, um senhor da guerra da Primeira Ordem. Eventualmente, ele é redimido e sacrifica-se para ajudar Rey a derrotar o ressuscitado Imperador Palpatine'
        ],
        "tokens": ['1t.png', '2t.png', '3t.png', '4t.png', '5t.png', '6t.png', '7t.png', '8t.png', '9t.png', '10t.png'],
        "wpp": ['1w.jpg', '2w.png', '3w.jpg', '4w.jpg', '5w.jpg', '6w.jpg', '7w.jpg', '8w.png', '9w.png', '10w.jpg'],
       
    },
    {
        "lado": "luz",
        "name": [ 'Luke Skywalker','Anakin Skywalker', 'obi-wan Kenobi', 'Mestre Yoda', 'qui-gon Jinn', 'Mance Windu', 'Rey'],
        "desc": [
            'Sendo considerado o Maior Jedi que ja existiu, Luke Skywalker foi o responsavel pelo fim do Império de Palpatine. Sendo descendente de Anakin, Luke tem uma proximidade maior que qualquer outro Jedi com a força, após seu treinamento completo foi capaz de derrotar Darth Vader e converte-lo novamente ao lado da luz.',
            'Conhecido nas Guerras Clônicas como "Herói sem medo", Anakin Skywalker foi o escolhido da força, aquele dito que traria o equilibrio de volta, mas não do jeito que os Jedis imaginavam. Encontrado por Qui-Gon Jinn e treinado por Obi-wan, Anakin foi um mestre Jedi extremamente talentoso, tendo uma conexão com a força incomparável, sendo dita como duas vezes mais poderoso que Darth Sidious, e um duelista melhor que o próprio Yoda, Anakin teve seu destaque nas Guerras Clônicas, onde após os acontecimentos acabou se voltando ao lado negro e sendo derrotado por Obi-wan, perdendo assim mais da metade de seu corpo e se tornando Darth Vader.',
            'Obi-Wan Kenobi foi um Mestre Jedi que desempenhou um papel crucial nos eventos que moldaram a galáxia. Kenobi nasceu no planeta Stewjon e foi treinado como Jedi por Qui-Gon Jinn. Ele derrotou o Lorde Sith Darth Maul, tornando-se um Cavaleiro Jedi. Kenobi treinou Anakin Skywalker, que foi profetizado como o Escolhido para restaurar o equilíbrio na Força. Durante as Guerras Clônicas, ele serviu como Alto General Jedi. Após a Grande Purga Jedi, Kenobi foi forçado ao exílio. Ele também foi mentor de Luke Skywalker, introduzindo-o aos caminhos da Força.',
            'Mestre Yoda é um membro de uma espécie desconhecida, pequeno em estatura com apenas 76 centímetros de altura, e tem pele verde e grandes orelhas. Yoda é extremamente antigo, vivendo por mais de 900 anos. Ele é conhecido por sua sabedoria profunda, habilidades poderosas na Força e habilidades excepcionais com um sabre de luz. Yoda serviu como o Grande Mestre do Conselho Jedi e foi um mentor para muitos Jedi ao longo de sua vida.',
            'Qui-Gon Jinn foi aprendiz de Conde Dookan e mestre de Obi-Wan, foi o responsavel por encontrar o escolhido, Anakin Skywalker e morto por Darth Maul em Ameaça fantasma. Apesar de não ser incrivelmente talentoso com o sabre, Qui-Gon é possivelmente uma das maiores referencias em conhecimento, sabedoria e entendimento da força, sendo capaz de obter a imortalidade atraves da força, e ensinando Yoda e Obi-wan a fazer o mesmo, canonicamente é dito como o primeiro personagem a conseguir tal proeza .',
            'Mace Windu foi um Mestre Jedi, serviu como membro do Alto Conselho Jedi e foi um General Jedi durante as Guerras Clônicas. Windu é conhecido por sua sabedoria, habilidades com a Força e destreza com o sabre de luz. Ele nasceu em Haruun Kal e liderou 212 Jedi em uma batalha em Geonosis, sendo morto por Darth Sidious e Anakin em Vingança dos Sith.',

            'Rey Skywalker, conhecida apenas como Rey antes de adotar o sobrenome Skywalker, é uma personagem central da trilogia sequencial de Star Wars. Uma catadora de sucata no planeta Jakku e evolui para uma poderosa Mestra Jedi. Descobrindo ser sensível à Força, Rey foi trinada por Luke Skywalker e Leia Organa. Rey possui uma conexão especial com Kylo Ren, conhecido como ‘diálogo da Força’, que desempenha um papel crucial em sua jornada. Após a morte de Palpatine, Rey adota o sobrenome Skywalker para honrar a memória de seus mentores e a linhagem que escolheu seguir, assumindo o legado dos Jedi'
            
        ],
        "tokens": ['1t.png', '2t.png', '3t.png', '4t.png', '5t.png', '6t.png', '7t.png', '8t.png', '9t.png', '10t.png'],
        "wpp": ['1w.jpg', '2w.jpg', '3w.jpg', '4w.jpg', '5w.jpg', '6w.jpg', '7w.jpg', '8w.jpg', '9w.jpg', '10w.jpg'],
       
    }]